import Foundation

enum ExerciseCatalog {
    static let all: [Exercise] = [
        ex("hip-raise", "Relevé de bassin", [.lowerAbs, .deepCore], .hipFlexion, .beginner, .quiet, .hipRaise,
           "Ramène les genoux puis décolle doucement le bassin, sans prendre d’élan.", "Expire en montant, inspire en contrôlant la descente.", neck: true, setup: "Allongé sur le dos, bras le long du corps, paumes au sol, genoux fléchis.", mistake: "Prendre de l’élan avec les jambes au lieu d’enrouler le bassin.", intensity: 1.1),
        ex("leg-raise", "Relevé de jambes", [.lowerAbs, .deepCore], .hipFlexion, .balanced, .quiet, .legRaise,
           "Plaque les lombaires au sol et abaisse les jambes seulement tant que le dos reste stable.", "Expire en remontant les jambes.", neck: true, setup: "Sur le dos, mains sous les fessiers, jambes tendues à quelques centimètres du sol.", mistake: "Laisser le bas du dos se creuser quand les jambes descendent.", intensity: 1.25),
        ex("bent-knee-raise", "Relevé de genoux", [.lowerAbs, .deepCore], .hipFlexion, .beginner, .quiet, .legRaise,
           "Garde les genoux fléchis à 90° et rapproche-les de la poitrine sans élan.", "Souffle lorsque les genoux reviennent.", neck: true, setup: "Sur le dos, genoux fléchis à 90°, tibias parallèles au sol.", mistake: "Ouvrir l’angle du genou pendant le mouvement.", intensity: 0.9),
        ex("lower-ab-jumps", "Groupés en planche", [.lowerAbs, .fullCore], .locomotion, .advanced, .dynamic, .mountainClimber,
           "Depuis la planche, ramène les deux pieds près des mains puis repars avec contrôle.", "Souffle sur chaque retour groupé.", setup: "En position de planche haute, mains sous les épaules, pieds joints.", mistake: "Laisser le bassin monter en pic à chaque saut.", intensity: 1.65),
        ex("scissors", "Ciseaux", [.lowerAbs, .deepCore], .hipFlexion, .balanced, .quiet, .scissors,
           "Croise les jambes tendues à faible amplitude, lombaires lourdes au sol.", "Respire régulièrement sans bloquer.", neck: true, setup: "Sur le dos, lombaires plaquées, jambes tendues à 20 cm du sol.", mistake: "Croiser trop haut : l’amplitude vient des hanches, pas des genoux.", intensity: 1.25),
        ex("flutter-kicks", "Battements", [.lowerAbs, .deepCore], .hipFlexion, .balanced, .quiet, .flutter,
           "Alterne de petits battements rapides, nombril rentré et bassin immobile.", "Expire longuement pendant quatre battements.", neck: true, setup: "Sur le dos, mains sous les fessiers, jambes tendues et décollées.", mistake: "Battre avec les genoux fléchis, ce qui relâche les abdos.", intensity: 1.2),
        ex("reverse-crunch", "Crunch inversé", [.lowerAbs, .deepCore], .flexion, .beginner, .quiet, .reverseCrunch,
           "Enroule le bassin vers les côtes sans lancer les jambes au-dessus de la tête.", "Expire pendant l’enroulement.", neck: true, setup: "Sur le dos, genoux ramenés au-dessus des hanches, bras au sol.", mistake: "Lancer les jambes derrière la tête au lieu d’enrouler le bassin.", intensity: 1.0),
        ex("toe-taps", "Talons alternés", [.lowerAbs, .deepCore], .antiExtension, .beginner, .quiet, .deadBug,
           "Depuis les jambes en tablette, touche le sol d’une pointe sans creuser le dos.", "Expire à chaque descente.", unilateral: true, neck: true, setup: "Sur le dos, jambes en tablette, bas du dos collé au sol.", mistake: "Descendre trop bas et perdre le contact des lombaires.", intensity: 0.8),

        ex("classic-crunch", "Crunch contrôlé", [.upperAbs], .flexion, .beginner, .quiet, .crunch,
           "Soulève les omoplates, le regard au plafond et les mains légères derrière la tête.", "Expire en rapprochant les côtes du bassin.", setup: "Sur le dos, genoux fléchis, pieds au sol, mains posées derrière la tête sans tirer.", mistake: "Tirer sur la nuque avec les mains pour monter plus haut.", intensity: 0.9),
        ex("toe-reach", "Toucher de pointes", [.upperAbs, .deepCore], .flexion, .balanced, .quiet, .toeReach,
           "Jambes au-dessus des hanches, tends les mains vers les chevilles sans tirer la nuque.", "Souffle à chaque montée.", setup: "Sur le dos, jambes tendues à la verticale au-dessus des hanches.", mistake: "Monter par à-coups d’épaules au lieu d’enrouler le buste.", intensity: 1.1),
        ex("explosive-crunch", "Crunch explosif", [.upperAbs, .fullCore], .flexion, .advanced, .dynamic, .crunch,
           "Monte vivement puis freine la descente; la puissance vient des abdos, pas de la nuque.", "Expiration brève en montant.", setup: "Sur le dos, genoux fléchis, bras le long du corps, prêt à monter vite.", mistake: "Se laisser retomber : la descente doit rester freinée.", intensity: 1.55),
        ex("long-lever-crunch", "Crunch bras tendus", [.upperAbs, .deepCore], .flexion, .advanced, .quiet, .crunch,
           "Garde les bras près des oreilles et décolle uniquement le haut du dos.", "Expire en montant, inspire en redescendant.", setup: "Sur le dos, bras tendus près des oreilles, genoux fléchis.", mistake: "Laisser les bras avancer devant : ils restent alignés avec la tête.", intensity: 1.35),

        ex("oblique-crunch", "Crunch oblique alterné", [.obliques, .upperAbs], .lateral, .beginner, .quiet, .obliqueCrunch,
           "Rapproche une côte de la hanche opposée puis change de côté sans tirer la tête.", "Expire sur chaque diagonale.", unilateral: true, setup: "Sur le dos, genoux fléchis, une main derrière la tête, coude ouvert.", mistake: "Tirer avec le coude au lieu de rapprocher les côtes de la hanche.", intensity: 1.0),
        ex("russian-twist", "Rotations russes", [.obliques, .fullCore], .rotation, .balanced, .quiet, .twist,
           "Grandis le dos, pivote les côtes et garde le bassin face à toi.", "Souffle au passage du milieu.", unilateral: true, setup: "Assis, buste incliné en arrière, talons posés ou décollés, mains jointes devant le sternum.", mistake: "Balancer les bras seuls : ce sont les côtes qui pivotent.", intensity: 1.25),
        ex("bicycle", "Bicyclette", [.obliques, .lowerAbs, .fullCore], .rotation, .balanced, .quiet, .bicycle,
           "Allonge une jambe pendant que l’épaule opposée tourne vers le genou; reste fluide.", "Expire à chaque changement de côté.", unilateral: true, setup: "Sur le dos, jambes en tablette, mains légères derrière la tête.", mistake: "Pédaler vite en tirant sur la nuque plutôt que de tourner le buste.", intensity: 1.45),
        ex("heel-taps", "Toucher de talons", [.obliques, .upperAbs], .lateral, .beginner, .quiet, .heelTap,
           "Épaules légèrement décollées, glisse une main vers le talon du même côté.", "Respire sur un rythme régulier.", unilateral: true, setup: "Sur le dos, genoux fléchis, talons près des fessiers, épaules légèrement décollées.", mistake: "Reposer les épaules entre chaque toucher.", intensity: 0.85),
        ex("side-plank", "Planche latérale", [.obliques, .deepCore], .lateral, .balanced, .quiet, .sidePlank,
           "Aligne épaules, bassin et pieds; pousse le sol et garde la taille haute.", "Respire lentement dans les côtes.", unilateral: true, neck: true, setup: "Sur le côté, coude sous l’épaule, pieds superposés, bassin décollé.", mistake: "Laisser le bassin descendre ou le buste basculer vers l’avant.", intensity: 1.3),
        ex("side-plank-dip", "Planche latérale, bassin", [.obliques, .deepCore], .lateral, .advanced, .quiet, .sidePlank,
           "En planche latérale, abaisse légèrement le bassin puis remonte sans tourner le buste.", "Expire à la remontée.", unilateral: true, neck: true, setup: "Position de planche latérale stable, main libre sur la hanche.", mistake: "Tourner le buste vers le sol pendant la descente.", intensity: 1.5),

        ex("forearm-plank", "Planche avant", [.deepCore, .fullCore], .antiExtension, .beginner, .quiet, .plank,
           "Pousse les avant-bras, serre fessiers et cuisses, garde une ligne longue des talons au crâne.", "Respire bas et lentement.", neck: true, setup: "Sur les avant-bras, coudes sous les épaules, pieds écartés largeur de bassin.", mistake: "Laisser le bassin s’affaisser ou monter en pointe.", intensity: 1.0),
        ex("shoulder-hold", "Planche haute", [.deepCore, .fullCore], .antiExtension, .beginner, .quiet, .plank,
           "Mains sous les épaules, repousse le sol et stabilise le bassin.", "Expire sans perdre l’alignement.", neck: true, setup: "Mains sous les épaules, bras tendus, corps en ligne des talons au crâne.", mistake: "Verrouiller les coudes en hyperextension.", intensity: 1.05),
        ex("plank-reach", "Planche bras tendu", [.deepCore, .fullCore], .antiExtension, .advanced, .quiet, .plankReach,
           "Depuis la planche, tends un bras devant toi sans laisser le bassin pivoter.", "Expire lorsque le bras s’allonge.", unilateral: true, neck: true, setup: "Planche haute, pieds un peu écartés pour élargir l’appui.", mistake: "Laisser le bassin pivoter quand le bras s’allonge.", intensity: 1.5),
        ex("mountain-climber", "Grimpeur", [.fullCore, .lowerAbs], .locomotion, .balanced, .dynamic, .mountainClimber,
           "Ramène les genoux sous la poitrine en gardant les épaules au-dessus des mains.", "Souffle sur deux appuis.", unilateral: true, neck: true, setup: "Planche haute, épaules à l’aplomb des mains, dos plat.", mistake: "Faire rebondir le bassin de haut en bas à chaque appui.", intensity: 1.6),
        ex("cross-climber", "Grimpeur croisé", [.obliques, .fullCore], .rotation, .advanced, .dynamic, .mountainClimber,
           "Dirige chaque genou vers le coude opposé tout en maintenant le haut du corps stable.", "Expire sur chaque diagonale.", unilateral: true, neck: true, setup: "Planche haute, appuis stables, regard légèrement en avant des mains.", mistake: "Tourner les épaules au lieu de faire travailler les obliques.", intensity: 1.7),
        ex("bear-hold", "Gainage de l’ours", [.deepCore, .fullCore], .antiExtension, .balanced, .quiet, .bearHold,
           "Décolle les genoux de quelques centimètres, dos plat, et pousse fort dans les mains pour garder les épaules loin des oreilles.", "Respire calmement malgré la tension.", neck: true, setup: "À quatre pattes, mains sous les épaules, genoux sous les hanches puis décollés.", mistake: "Monter les genoux trop haut, ce qui arrondit le dos.", intensity: 1.2),
        ex("bear-shoulder-tap", "Ours, épaules alternées", [.deepCore, .obliques], .antiExtension, .advanced, .quiet, .bearHold,
           "En position ours, touche l’épaule opposée sans déplacer le bassin.", "Expire lors de chaque toucher.", unilateral: true, neck: true, setup: "Position de l’ours stable, genoux à quelques centimètres du sol.", mistake: "Laisser le bassin rouler d’un côté à l’autre à chaque toucher.", intensity: 1.45),
        ex("hollow-hold", "Gainage creux", [.deepCore, .lowerAbs], .antiExtension, .advanced, .quiet, .hollowHold,
           "Écrase les lombaires au sol et éloigne bras et jambes seulement si le contact reste solide.", "Expire longuement, côtes fermées.", neck: true, setup: "Sur le dos, lombaires écrasées au sol, bras et jambes tendus et décollés.", mistake: "Éloigner bras et jambes au point de décoller le bas du dos.", intensity: 1.5),
        ex("dead-bug", "Dead bug", [.deepCore, .lowerAbs], .antiExtension, .beginner, .quiet, .deadBug,
           "Allonge bras et jambe opposés tout en gardant le tronc parfaitement stable.", "Expire pendant l’allongement.", unilateral: true, neck: true, setup: "Sur le dos, bras tendus vers le plafond, jambes en tablette.", mistake: "Allonger trop vite et laisser le dos se creuser.", intensity: 0.85),
        ex("v-sit", "Maintien en V", [.fullCore, .lowerAbs], .hipFlexion, .advanced, .quiet, .vSit,
           "Tiens l’équilibre sur les ischions, poitrine ouverte et tibias parallèles au sol.", "Respire sans arrondir davantage le dos.", neck: true, setup: "Assis, en équilibre sur les ischions, buste ouvert et tibias parallèles au sol.", mistake: "Arrondir le dos et se laisser tomber en arrière.", intensity: 1.45),
        ex("v-sit-extension", "Extension en V", [.fullCore, .lowerAbs], .hipFlexion, .athlete, .quiet, .vSit,
           "Depuis le V, éloigne simultanément jambes et buste puis reviens compact.", "Expire au retour.", neck: true, setup: "Départ en V compact, mains le long des cuisses.", mistake: "Perdre l’équilibre vers l’arrière pendant l’extension.", intensity: 1.8),

        ex("bird-dog", "Bird dog", [.deepCore, .lowerBack], .posterior, .beginner, .quiet, .birdDog,
           "Allonge bras et jambe opposés, hanches face au sol et nuque longue.", "Expire pendant l’allongement.", unilateral: true, neck: true, setup: "À quatre pattes, mains sous les épaules, genoux sous les hanches.", mistake: "Lever la jambe plus haut que la hanche et cambrer le dos.", intensity: 0.75),
        ex("superman", "Superman", [.lowerBack, .deepCore], .posterior, .balanced, .quiet, .superman,
           "Décolle légèrement bras et jambes en gardant le regard vers le sol.", "Expire en montant, ne force pas l’amplitude.", neck: true, setup: "Sur le ventre, bras allongés devant, front vers le sol.", mistake: "Casser la nuque en levant le menton.", intensity: 1.0),
        ex("glute-bridge", "Pont fessier", [.lowerBack, .deepCore], .posterior, .beginner, .quiet, .bridge,
           "Pousse dans les pieds et monte le bassin jusqu’à aligner épaules, hanches et genoux.", "Expire en montant.", neck: true, setup: "Sur le dos, pieds à plat près des fessiers, bras le long du corps.", mistake: "Monter en cambrant le bas du dos plutôt qu’en serrant les fessiers.", intensity: 0.7),
        ex("bridge-march", "Marche en pont", [.deepCore, .lowerBack], .posterior, .advanced, .quiet, .bridgeMarch,
           "Depuis le pont, décolle un pied puis l’autre sans laisser le bassin tomber.", "Expire sur chaque marche.", unilateral: true, neck: true, setup: "Bassin déjà monté et stable, appuis fermes sur les deux pieds.", mistake: "Laisser une hanche tomber quand le pied décolle.", intensity: 1.25),
        ex("plank-knee-tap", "Planche, genoux alternés", [.deepCore, .lowerAbs], .antiExtension, .balanced, .quiet, .plank,
           "Depuis la planche, pose un genou au sol à la fois sans changer la hauteur du bassin.", "Souffle à chaque appui.", unilateral: true, neck: true, setup: "Planche avant sur les avant-bras, corps aligné.", mistake: "Faire monter le bassin pour aller chercher le sol.", intensity: 1.15),
        ex("seated-knee-tuck", "Genoux-poitrine assis", [.lowerAbs, .fullCore], .hipFlexion, .balanced, .quiet, .seatedTuck,
           "Assis en appui léger sur les mains, éloigne puis ramène les genoux avec le buste fier.", "Expire en ramenant les genoux.", neck: true, setup: "Assis, mains en appui léger derrière les hanches, pieds décollés.", mistake: "S’asseoir sur le bas du dos au lieu de rester grandi.", intensity: 1.25),
        ex("plank-jacks", "Planche sautée", [.fullCore, .obliques], .locomotion, .advanced, .dynamic, .plank,
           "Écarte et resserre les pieds en gardant le bassin bas et stable.", "Respire sur un rythme régulier.", neck: true, setup: "Planche haute ou sur avant-bras, pieds joints.", mistake: "Laisser le bassin osciller de haut en bas à chaque écart.", intensity: 1.75)
    ]

    private static func ex(
        _ id: String,
        _ name: String,
        _ zones: Set<MuscleZone>,
        _ family: MovementFamily,
        _ minimumDifficulty: WorkoutDifficulty,
        _ impact: ExerciseImpact,
        _ motion: MotionKind,
        _ instruction: String,
        _ breathing: String,
        unilateral: Bool = false,
        neck: Bool = false,
        setup: String,
        mistake: String,
        intensity: Double
    ) -> Exercise {
        Exercise(
            id: id,
            name: name,
            zones: zones,
            family: family,
            minimumDifficulty: minimumDifficulty,
            impact: impact,
            motion: motion,
            setup: setup,
            instruction: instruction,
            breathing: breathing,
            mistake: mistake,
            unilateral: unilateral,
            neckFriendly: neck,
            intensity: intensity
        )
    }
}

